name: "GitHub Agent"
description: "Autonomous GitHub Agent powered by OpenCode/Codex"
author: "Your Organization"

inputs:
  github_token:
    description: "GitHub token for API access (use a PAT if GITHUB_TOKEN cannot create PRs)"
    required: true
    default: ${{ github.token }}
  openai_api_key:
    description: "OpenAI API key for OpenCode/Codex (also set as CODEX_API_KEY)"
    required: true
  opencode_bin:
    description: "CLI binary to run (opencode or codex)"
    required: false
    default: "codex"
  max_rounds:
    description: "Maximum number of agent rounds per issue/PR"
    required: false
    default: "3"
  auto_coder:
    description: "Automatically run issue-coder when issue-chatter sets requires_coding_agent (true/false)"
    required: false
    default: "true"
  model_name:
    description: "LLM model name (e.g., gpt-4o, claude-sonnet-4-20250514)"
    required: false
    default: ""
  model_reasoning_effort:
    description: "Codex reasoning effort (e.g., low/medium/high/xhigh)"
    required: false
    default: "xhigh"
  max_tokens:
    description: "Maximum tokens for LLM response"
    required: false
    default: ""
  fallback_models:
    description: "Comma-separated fallback models list"
    required: false
    default: ""
  response_language:
    description: "Response language (en/zh-CN)"
    required: false
    default: ""
  anthropic_api_key:
    description: "Anthropic API key for Claude models"
    required: false
    default: ""
  anthropic_api_base:
    description: "Anthropic API base URL (optional, for custom endpoints)"
    required: false
    default: ""
  gemini_api_key:
    description: "Google API key for Gemini models"
    required: false
    default: ""
  gemini_api_base:
    description: "Gemini API base URL (optional, for custom endpoints)"
    required: false
    default: ""
  openai_api_base:
    description: "OpenAI API base URL (optional, for custom endpoints or compatible APIs)"
    required: false
    default: ""
  disable_response_storage:
    description: "Disable storing responses in Codex CLI (true/false)"
    required: false
    default: "true"

outputs:
  current_round:
    description: "Current round number"
  requires_coding_agent:
    description: "Whether coding agent is needed"

runs:
  using: "node20"
  main: "dist/main.js"

branding:
  icon: "cpu"
  color: "purple"
