name: GitHub Agent

on:
  issues:
    types: [opened, edited, reopened]
  issue_comment:
    types: [created]
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  agent:
    runs-on: ubuntu-latest
    # 排除 bot 触发，防止无限循环
    if: |
      github.actor != 'dependabot[bot]' &&
      github.actor != 'github-actions[bot]'
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: your-org/github-agent@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          openai_api_key: ${{ secrets.OPENAI_API_KEY }}
          # openai_api_base: ${{ secrets.OPENAI_API_BASE }}
